export function getLocalizedDidactic(id, locale) {
  const content = {
    'pt-BR': {
      prompt: {
        badge: 'Real do modelo',
        input: 'Texto bruto (string).',
        transform: 'Nenhuma: este é o ponto de partida.',
        output: 'O próprio texto e seu tamanho.',
        why: 'Transformers não leem strings diretamente; precisamos converter isso para ids.',
        caveats: ['O backend limita o tamanho do prompt por simplicidade.'],
      },
      tokenization: {
        badge: 'Real do modelo',
        input: 'Texto.',
        transform: 'O tokenizer divide em sub-tokens e mapeia para ids no vocabulário.',
        output: 'Lista de tokens e ids.',
        why: 'O modelo só entende ids; a tokenização afeta atenção, logits e geração.',
        caveats: ['Token não é igual a palavra. Espaço pode fazer parte do token.'],
      },
      embedding: {
        badge: 'Resumo',
        input: 'Ids de tokens.',
        transform: 'O forward produz hidden states; mostramos um resumo da última camada.',
        output: 'Vetores truncados por token.',
        why: 'Hidden states carregam a representação contextual interna do modelo.',
        caveats: ['Isto não é embedding puro; é estado oculto já contextualizado.'],
      },
      attention: {
        badge: 'Resumo',
        input: 'Hidden states do forward.',
        transform: 'Extraímos attentions e fazemos média das heads da última camada.',
        output: 'Heatmap token×token e pesos do token em foco.',
        why: 'Ajuda a ver como o modelo distribui importância sobre o contexto.',
        caveats: ['Atenção não explica tudo sozinha.', 'Média entre heads é uma simplificação didática.'],
      },
      residual: {
        badge: 'Proxy visual',
        input: 'Hidden state do último token.',
        transform: 'Mostramos um recorte do vetor final.',
        output: 'Sequência curta de valores.',
        why: 'Torna visível que existe um estado interno sendo atualizado.',
        caveats: ['Não separa FFN de residual; é só um proxy visual.'],
      },
      logits: {
        badge: 'Real do modelo',
        input: 'Estado final do modelo.',
        transform: 'A camada final produz um score para cada id do vocabulário.',
        output: 'Top-k candidatos com logit e probabilidade real.',
        why: 'É daqui que sai a distribuição do próximo token.',
        caveats: ['Logit é score bruto; probabilidade é pós-softmax.'],
      },
      decode: {
        badge: 'Real do modelo',
        input: 'Distribuição de próximos tokens.',
        transform: 'A estratégia escolhida seleciona o próximo token e concatena ao texto.',
        output: 'Novo texto e trilha temporal da geração.',
        why: 'Geração autoregressiva repete esse ciclo token a token.',
        caveats: ['Greedy é só uma das estratégias de decoding; top-k e top-p podem amostrar do pool candidato.'],
      },
    },
    en: {
      prompt: {
        badge: 'Model reality',
        input: 'Raw text (string).',
        transform: 'None: this is the starting point.',
        output: 'The text itself and its length.',
        why: 'Transformers do not read strings directly; they need ids.',
        caveats: ['The backend limits prompt length for simplicity.'],
      },
      tokenization: {
        badge: 'Model reality',
        input: 'Text.',
        transform: 'The tokenizer splits it into sub-tokens and maps them to vocabulary ids.',
        output: 'A list of tokens and ids.',
        why: 'The model only understands ids; tokenization affects attention, logits, and generation.',
        caveats: ['A token is not the same as a whole word. Spaces may be part of the token.'],
      },
      embedding: {
        badge: 'Summary',
        input: 'Token ids.',
        transform: 'The forward pass produces hidden states; we show a summary of the last layer.',
        output: 'Truncated vectors for each token.',
        why: 'Hidden states carry the model internal contextual representation.',
        caveats: ['This is not a pure embedding; it is an already contextualized hidden state.'],
      },
      attention: {
        badge: 'Summary',
        input: 'Hidden states from the forward pass.',
        transform: 'We extract attentions and average the heads of the last layer.',
        output: 'A token×token heatmap and weights for the focus token.',
        why: 'It helps you see how the model spreads importance across the context.',
        caveats: ['Attention alone is not a full explanation.', 'Averaging heads is a teaching simplification.'],
      },
      residual: {
        badge: 'Visual proxy',
        input: 'The last token hidden state.',
        transform: 'We show a slice of the final vector.',
        output: 'A short sequence of values.',
        why: 'It makes the model internal state feel concrete.',
        caveats: ['It does not separate FFN from residual; it is only a visual proxy.'],
      },
      logits: {
        badge: 'Model reality',
        input: 'The final model state.',
        transform: 'The final layer produces a score for every vocabulary id.',
        output: 'Top-k candidates with logit and true probability.',
        why: 'This is where the next-token distribution comes from.',
        caveats: ['Logit is the raw score; probability is post-softmax.'],
      },
      decode: {
        badge: 'Model reality',
        input: 'The next-token distribution.',
        transform: 'The selected strategy chooses the next token and appends it to the text.',
        output: 'New text and a temporal generation trace.',
        why: 'Autoregressive generation repeats this cycle token by token.',
        caveats: ['Greedy is only one decoding strategy; top-k and top-p can sample from a candidate pool.'],
      },
    },
    es: {
      prompt: {
        badge: 'Real del modelo',
        input: 'Texto bruto (string).',
        transform: 'Ninguna: este es el punto de partida.',
        output: 'El propio texto y su tamaño.',
        why: 'Los transformers no leen strings directamente; necesitan ids.',
        caveats: ['El backend limita la longitud del prompt por simplicidad.'],
      },
      tokenization: {
        badge: 'Real del modelo',
        input: 'Texto.',
        transform: 'El tokenizer lo divide en sub-tokens y lo mapea a ids del vocabulario.',
        output: 'Lista de tokens e ids.',
        why: 'El modelo solo entiende ids; la tokenización afecta atención, logits y generación.',
        caveats: ['Un token no equivale a una palabra completa. El espacio puede ser parte del token.'],
      },
      embedding: {
        badge: 'Resumen',
        input: 'Ids de tokens.',
        transform: 'El forward produce hidden states; mostramos un resumen de la última capa.',
        output: 'Vectores truncados por token.',
        why: 'Los hidden states contienen la representación contextual interna del modelo.',
        caveats: ['Esto no es embedding puro; es un estado oculto ya contextualizado.'],
      },
      attention: {
        badge: 'Resumen',
        input: 'Hidden states del forward.',
        transform: 'Extraemos attentions y promediamos las heads de la última capa.',
        output: 'Heatmap token×token y pesos del token en foco.',
        why: 'Ayuda a ver cómo el modelo reparte importancia sobre el contexto.',
        caveats: ['La atención por sí sola no explica todo.', 'Promediar heads es una simplificación didáctica.'],
      },
      residual: {
        badge: 'Proxy visual',
        input: 'Hidden state del último token.',
        transform: 'Mostramos un recorte del vector final.',
        output: 'Secuencia corta de valores.',
        why: 'Hace visible que existe un estado interno en actualización.',
        caveats: ['No separa FFN de residual; es solo un proxy visual.'],
      },
      logits: {
        badge: 'Real del modelo',
        input: 'Estado final del modelo.',
        transform: 'La capa final produce un score para cada id del vocabulario.',
        output: 'Top-k de candidatos con logit y probabilidad real.',
        why: 'De aquí sale la distribución del siguiente token.',
        caveats: ['Logit es el score bruto; probabilidad es post-softmax.'],
      },
      decode: {
        badge: 'Real del modelo',
        input: 'Distribución del siguiente token.',
        transform: 'La estrategia elegida selecciona el siguiente token y lo concatena al texto.',
        output: 'Texto nuevo y traza temporal de generación.',
        why: 'La generación autoregresiva repite este ciclo token a token.',
        caveats: ['Greedy es solo una estrategia de decoding; top-k y top-p pueden muestrear desde el pool candidato.'],
      },
    },
  };

  return content[locale]?.[id] ?? content.en[id] ?? null;
}
